# Generated by Django 2.1 on 2018-08-25 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='Versión')),
                ('consultas', models.TextField(max_length=1500, verbose_name='Consultas Relevantes')),
                ('informacion', models.TextField(max_length=1500, verbose_name='Información del proyecto')),
                ('estatus', models.CharField(blank=True, choices=[('t', 'Terminado'), ('d', 'En Desarrollo'), ('p', 'Pausado'), ('c', 'Cancelado')], default='d', help_text='Avance del Desarrollo', max_length=1)),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Proyecto')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('descripcion', models.TextField(max_length=1500, verbose_name='Descripción')),
                ('notas', models.TextField(max_length=1500, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
            ],
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Proyecto'),
        ),
    ]
